// <auto-generated />
using System;
using ApiProAnalytics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiProAnalytics.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504130247_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ApiProAnalytics.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamMemberId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamMemberId");

                    b.ToTable("ActivityLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionType = "completed",
                            CreatedAt = new DateTime(2024, 5, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "завершила задачу",
                            ProjectName = "Дизайн главной страницы",
                            TeamMemberId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActionType = "updated",
                            CreatedAt = new DateTime(2024, 5, 21, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "обновил проект",
                            ProjectName = "Мобильное приложение",
                            TeamMemberId = 2
                        },
                        new
                        {
                            Id = 3,
                            ActionType = "added",
                            CreatedAt = new DateTime(2024, 5, 21, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "добавила файл",
                            ProjectName = "Презентация проекта",
                            TeamMemberId = 3
                        },
                        new
                        {
                            Id = 4,
                            ActionType = "created",
                            CreatedAt = new DateTime(2024, 5, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "создал задачу",
                            ProjectName = "Настройка аналитики",
                            TeamMemberId = 4
                        });
                });

            modelBuilder.Entity("ApiProAnalytics.Models.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CalendarEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#3B82F6",
                            EndTime = new TimeSpan(0, 11, 0, 0, 0),
                            EventDate = new DateTime(2024, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Планёрка команды",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#10B981",
                            EndTime = new TimeSpan(0, 15, 30, 0, 0),
                            EventDate = new DateTime(2024, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            Title = "Презентация проекта",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Color = "#F59E0B",
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            EventDate = new DateTime(2024, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeSpan(0, 11, 0, 0, 0),
                            Title = "Код-ревью",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Color = "#8B5CF6",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            EventDate = new DateTime(2024, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartTime = new TimeSpan(0, 15, 0, 0, 0),
                            Title = "Встреча с клиентом",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("ApiProAnalytics.Models.ProgressSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("EfficiencyIndex")
                        .HasColumnType("REAL");

                    b.Property<double>("OverallProgress")
                        .HasColumnType("REAL");

                    b.Property<double>("ProgressChangePercent")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TasksDone")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TasksDoneChangePct")
                        .HasColumnType("REAL");

                    b.Property<int>("TasksInProgress")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TasksInProgressChangePct")
                        .HasColumnType("REAL");

                    b.Property<int>("TeamActiveCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeSavedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ProgressSnapshots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EfficiencyIndex = 8.9000000000000004,
                            OverallProgress = 75.0,
                            ProgressChangePercent = 12.0,
                            RecordedAt = new DateTime(2024, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TasksDone = 142,
                            TasksDoneChangePct = 18.0,
                            TasksInProgress = 28,
                            TasksInProgressChangePct = -5.0,
                            TeamActiveCount = 12,
                            TimeSavedMinutes = 1455,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("ApiProAnalytics.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DueDate = new DateTime(2024, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "High",
                            Status = "InProgress",
                            Title = "Разработать дизайн системы",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DueDate = new DateTime(2024, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Medium",
                            Status = "InProgress",
                            Title = "Верстка главной страницы",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            DueDate = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Low",
                            Status = "InProgress",
                            Title = "Интеграция с API",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            DueDate = new DateTime(2024, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Medium",
                            Status = "Review",
                            Title = "Написать unit-тесты",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            DueDate = new DateTime(2024, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "High",
                            Status = "Done",
                            Title = "Настройка CI/CD",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            DueDate = new DateTime(2024, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Low",
                            Status = "Done",
                            Title = "Документация по API",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            DueDate = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "High",
                            Status = "InProgress",
                            Title = "Дизайн мобильного приложения",
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            DueDate = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "Medium",
                            Status = "Review",
                            Title = "Оптимизация базы данных",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("ApiProAnalytics.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Анна Петрова",
                            IsActive = true,
                            Role = "Дизайнер"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Сергей Смирнов",
                            IsActive = true,
                            Role = "Разработчик"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Мария Кузнецова",
                            IsActive = true,
                            Role = "Аналитик"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Дмитрий Волков",
                            IsActive = true,
                            Role = "Разработчик"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Елена Соколова",
                            IsActive = true,
                            Role = "Тестировщик"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Алексей Морозов",
                            IsActive = true,
                            Role = "DevOps"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Наталья Козлова",
                            IsActive = true,
                            Role = "PM"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Игорь Новиков",
                            IsActive = true,
                            Role = "Разработчик"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Ольга Попова",
                            IsActive = true,
                            Role = "Дизайнер"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Максим Лебедев",
                            IsActive = true,
                            Role = "Разработчик"
                        },
                        new
                        {
                            Id = 11,
                            FullName = "Татьяна Орлова",
                            IsActive = true,
                            Role = "QA"
                        },
                        new
                        {
                            Id = 12,
                            FullName = "Роман Киселёв",
                            IsActive = true,
                            Role = "Backend"
                        });
                });

            modelBuilder.Entity("ApiProAnalytics.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Иван Иванов",
                            PasswordHash = "Hba0WEVnPlBQNRk8kAWFBHqqHAhqse4YQ/pCjWV52tI=",
                            Role = "Менеджер проекта",
                            Username = "ivan"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Анна Петрова",
                            PasswordHash = "Hba0WEVnPlBQNRk8kAWFBHqqHAhqse4YQ/pCjWV52tI=",
                            Role = "Дизайнер",
                            Username = "anna"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Сергей Смирнов",
                            PasswordHash = "Hba0WEVnPlBQNRk8kAWFBHqqHAhqse4YQ/pCjWV52tI=",
                            Role = "Разработчик",
                            Username = "sergey"
                        });
                });

            modelBuilder.Entity("ApiProAnalytics.Models.ActivityLog", b =>
                {
                    b.HasOne("ApiProAnalytics.Models.TeamMember", "TeamMember")
                        .WithMany()
                        .HasForeignKey("TeamMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeamMember");
                });

            modelBuilder.Entity("ApiProAnalytics.Models.CalendarEvent", b =>
                {
                    b.HasOne("ApiProAnalytics.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiProAnalytics.Models.ProgressSnapshot", b =>
                {
                    b.HasOne("ApiProAnalytics.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiProAnalytics.Models.Task", b =>
                {
                    b.HasOne("ApiProAnalytics.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
